export const CHANGE_VALUE = 'CHANGE_VALUE';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const UPDATE_EXCHANGE_RATES = 'UPDATE_EXCHANGE_RATES';
export const RECEIVE_EXCHANGE_RATES = 'RECEIVE_EXCHANGE_RATES';
